name: "Kwiat Quantum Information Group"
description: "Our group website"

url: "http://research.physics.illinois.edu/QI/Photonics"
baseurl: ""
paper-path: "papers/My Collection.Data/PDF"

markdown: rdiscount
permalink: pretty
highlighter: null
excerpt_separator: <!--more-->
encoding: utf-8

gems:
  - jekyll-sitemap